print("=====AI CAREER TWIN=====")
name=input("Enter your name:")
target=input("Enter yor target job:")
java=int(input("Java level(1-10):"))
dsa=int(input("DSA level(1-10):"))
python=int(input("Python level(1-10):"))
sql=int(input("SQL level(1-10):"))
ml=int(input("ML level(1-10):"))

print("\n===== YOUR CAREER PROFILE =====")
print("Name:",name)
print("Target:",target)
print("Java:",java)
print("DSA:",dsa)
print("Python:",python)
print("SQL:",sql)
print("ML:",ml)